server:
  port: 8083
spring:
  data:
    solr:
      host: http://127.0.0.1:8080/solr
    thymeleaf:
      cache: false
      mode: LEGACYHTML5
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1905
    username: root
    password: 123

